import { useState } from "react";
import RiskGauge from "../components/RiskGauge";
import EvidenceCard from "../components/EvidenceCard";
import RelayPath from "../components/RelayPath";
import CampaignGraph from "../components/CampaignGraph";
import { mapApiResponseToReportShape } from "../utils/mapApiResponse";

const value = (item, fallback = "Not available") => item ?? fallback;
const Status = ({ label, result }) => <div className="auth-row"><span>{label}</span><b className={String(result).toLowerCase() === "pass" ? "pass" : String(result).toLowerCase() === "fail" ? "fail" : "unknown"}>{value(result)}</b></div>;

export default function InvestigationReportPage({ apiResponse, onNewInvestigation }) {
  const [tab, setTab] = useState("Overview");
  if (!apiResponse) return <main className="report"><p>No investigation data available. Try analyzing an email first.</p></main>;
  const data = mapApiResponseToReportShape(apiResponse);
  const domain = data.domain_info;
  const auth = apiResponse.header_auth || {};
  const triggeredBy = data.triggered_by;
  const tabs = ["Overview", "Email", "Headers", "URLs & Domains", "Infrastructure", "Fingerprint", "Correlation"];
  const attackNodes = [["EMAIL", apiResponse.from_header || "Sender unavailable", "Observed"], ["URL", data.url || "No URL observed", data.url ? "Observed" : null], ["DOMAIN", domain?.domain || "No domain observed", domain ? "Observed" : null], ["IP", domain?.ip || "No resolved IP", domain?.ip ? "Observed" : null], ["ASN / HOST", domain?.asn || domain?.hosting || "No host data", domain?.asn || domain?.hosting ? "Observed" : null], ["RELATED CASES", data.campaign_correlation ? `${data.campaign_correlation.matched_investigations} related` : "No matches found", data.campaign_correlation ? "Correlated" : null]];
  const rawPhishingScore = apiResponse.classifier?.phishing_score;
  const contentFinding = rawPhishingScore != null ? `${(rawPhishingScore <= 1 ? rawPhishingScore * 100 : rawPhishingScore).toFixed(1)}% phishing score` : "No content score returned";
  const infraFinding = data.infrastructure_evidence[0] || (domain ? `Domain: ${domain.domain}` : "No infrastructure indicators returned");

  return <main className="report investigation-report">
    <div className="breadcrumb"><button onClick={onNewInvestigation}>← Investigations</button><span className="mono">CASE #{String(data.investigation_id).slice(-8).toUpperCase()}</span><span>{data.analyzed_at || "Date unavailable"}</span>{triggeredBy && <span className="mono">Triggered by {value(triggeredBy.user_id, "unknown user")} · {value(triggeredBy.ip_address, "unknown IP")} · {value(triggeredBy.triggered_at, "unknown time")}</span>}</div>
    <section className="case-header"><div className="case-gauge"><RiskGauge score={data.risk_score} level={data.risk_level} /></div><div className="case-copy"><div className={`risk-label ${data.risk_level.toLowerCase()}`}>{data.risk_level.toUpperCase()} RISK</div><h1>{data.threat_label}</h1><div className="mail-metadata"><div><small>SUBJECT</small><strong>{value(apiResponse.subject)}</strong></div><div><small>FROM</small><strong className="mono">{value(apiResponse.from_header)}</strong></div></div></div><div className="case-actions"><button className="export-button" onClick={() => window.print()}>Export report</button><button className="new-report-button" onClick={() => setTab("Email")}>View raw email</button></div></section>
    <nav className="investigation-tabs">{tabs.map((name) => <button className={tab === name ? "active" : ""} onClick={() => setTab(name)} key={name}>{name}</button>)}</nav>
    {tab === "Overview" && <>
      <section className="summary-grid"><article><small>CONTENT</small><strong>{contentFinding}</strong><p>{apiResponse.classifier?.reasons?.[0] || "No content finding available."}</p></article><article><small>AUTHENTICATION</small><Status label="SPF" result={auth.spf} /><Status label="DMARC" result={auth.dmarc} /><p>DKIM status is not returned by this API.</p></article><article><small>INFRASTRUCTURE</small><strong className="mono">{domain?.domain || "No domain observed"}</strong><p>{infraFinding}</p></article><article><small>CORRELATION</small><strong>{data.campaign_correlation ? `${data.campaign_correlation.matched_investigations} related investigations` : "No related cases"}</strong><p>{data.campaign_correlation ? `Confidence ${value(data.campaign_correlation.confidence, "n/a")} · Cohesion ${value(data.campaign_correlation.cohesion, "n/a")}` : "No campaign correlation returned."}</p></article></section>
      <section className="section attack-section"><div className="section-head"><div><div className="section-kicker">INVESTIGATION CHAIN</div><div className="section-title">Attack path</div></div><div className="section-sub">Connections reflect observed analysis data.</div></div><div className="attack-path">{attackNodes.map(([title, detail, status], index) => <div className="attack-step" key={title}><article><small>{title}</small><strong className="mono">{detail}</strong>{status && <span>{status}</span>}</article>{index < attackNodes.length - 1 && <i>↓</i>}</div>)}</div></section>
      <section className="section"><div className="section-head"><div><div className="section-kicker">EVIDENCE-BASED VERDICT</div><div className="section-title">Why this score?</div></div><div className="final-risk"><small>FINAL RISK</small><b>{data.risk_score}<em>/100</em></b></div></div><div className="score-layout"><div className="score-categories"><div><small>CONTENT ANALYSIS</small><strong>{contentFinding}</strong></div><div><small>URL INTELLIGENCE</small><strong>{data.url || "No URL intelligence returned"}</strong></div><div><small>AUTHENTICATION</small><strong>SPF {value(auth.spf)} · DMARC {value(auth.dmarc)}</strong></div><div><small>INFRASTRUCTURE</small><strong>{infraFinding}</strong></div></div><div className="evidence-grid">{data.reasons.length ? data.reasons.map((reason) => <EvidenceCard reason={reason} key={reason.id} />) : <p className="empty-state">No discrete evidence items were returned for this analysis.</p>}</div></div></section>
      <section className="section"><div className="section-head"><div><div className="section-kicker">MAIL ROUTING FORENSICS</div><div className="section-title">Forensic relay trace</div></div><div className="section-sub">Received headers only — click a hop for details.</div></div>{data.relay_path.length ? <><RelayPath hops={data.relay_path} /><div className="hop-table"><div className="hop-table-header"><span>HOP</span><span>HOST</span><span>IP</span><span>STATUS</span></div>{data.relay_path.map((hop) => <div key={hop.label}><span>{hop.label}</span><span className="mono">{hop.sub}</span><span className="mono">{hop.ip}</span><span>{hop.trusted ? "Trusted boundary" : hop.verified ? "Verified" : "Observed"}</span></div>)}</div></> : <div className="empty-state">No parsed Received-hop chain was returned.</div>}</section>
      <section className="section"><div className="section-head"><div><div className="section-kicker">DOMAIN INTELLIGENCE</div><div className="section-title">Registration, TLS & reputation</div></div></div>{domain ? <div className="score-categories"><div><small>REGISTRAR</small><strong>{value(domain.registrar)}</strong></div><div><small>DOMAIN AGE</small><strong>{domain.age_days != null ? `${domain.age_days} days` : "Not available"}</strong></div><div><small>TLS ISSUER / STATUS</small><strong>{value(domain.tls_issuer)} · {value(domain.tls_status)}</strong></div><div><small>ASN / HOSTING</small><strong>{domain.asn || domain.hosting ? `${value(domain.asn, "")} ${value(domain.hosting, "")}`.trim() : "Not available"}</strong></div><div><small>COUNTRY</small><strong>{value(domain.country)}</strong></div><div><small>BLOCKLIST HITS</small><strong>{domain.found_on_lists?.length ? domain.found_on_lists.join(", ") : "None"}</strong></div></div> : <div className="empty-state">No domain intelligence was returned for this investigation.</div>}</section>
      <section className="section campaign-section"><div className="section-head"><div><div className="section-kicker">CAMPAIGN INTELLIGENCE</div><div className="section-title">Infrastructure correlation</div></div></div>{data.campaign_correlation ? <><div className="corr-banner">Matched <strong>{data.campaign_correlation.matched_investigations} related investigations</strong> from real stored correlation data. Confidence {value(data.campaign_correlation.confidence, "n/a")} · Cohesion {value(data.campaign_correlation.cohesion, "n/a")}{data.campaign_correlation.cohesion_warning ? ` · ⚠ ${data.campaign_correlation.cohesion_warning}` : ""}</div><CampaignGraph nodes={data.campaign_correlation.nodes} edges={data.campaign_correlation.edges} /></> : <div className="empty-state">No campaign matches were returned for this investigation.</div>}</section>
    </>}
    {tab === "Fingerprint" && <section className="section detail-tab"><div className="section-kicker">FINGERPRINT</div><div className="section-title">Content fingerprint & brand targeting</div>{data.fingerprint ? <div className="score-categories"><div><small>STRUCTURAL HASH</small><strong className="mono">{value(data.fingerprint.structural_hash)}</strong></div><div><small>SKELETON TYPE</small><strong>{value(data.fingerprint.skeleton_type)}</strong></div><div><small>TARGETED BRANDS</small><strong>{data.fingerprint.targeted_brands.length ? data.fingerprint.targeted_brands.join(", ") : "None detected"}</strong></div><div><small>TYPOSQUAT MATCHES</small>{data.fingerprint.typosquat_matches.length ? <ul>{data.fingerprint.typosquat_matches.map((m, i) => <li key={i} className="mono">{typeof m === "string" ? m : `${m.domain || "?"} → mimics "${m.matched_brand || "?"}" (matched "${m.matched_chunk || "?"}", edit distance ${m.edit_distance ?? "?"})`}</li>)}</ul> : <strong>None detected</strong>}</div></div> : <div className="empty-state">No fingerprint data was returned for this investigation.</div>}</section>}
    {tab === "Email" && <section className="section detail-tab"><div className="section-kicker">EMAIL</div><div className="section-title">Raw email</div>{apiResponse.raw_email ? <pre>{typeof apiResponse.raw_email === "string" ? apiResponse.raw_email : (apiResponse.raw_email.raw_content || JSON.stringify(apiResponse.raw_email, null, 2))}</pre> : <div className="empty-state">Raw email content was not returned for this investigation (fetch with ?full=true, or it may not be archived).</div>}</section>}
    {tab !== "Overview" && tab !== "Fingerprint" && tab !== "Email" && <section className="section detail-tab"><div className="section-kicker">{tab.toUpperCase()}</div><div className="section-title">Detailed {tab.toLowerCase()}</div><pre>{JSON.stringify(tab === "Headers" ? auth : tab === "Correlation" ? apiResponse.campaign_correlation : tab === "Infrastructure" ? apiResponse.infrastructure_risk : tab === "URLs & Domains" ? apiResponse.domains : { subject: apiResponse.subject, from: apiResponse.from_header }, null, 2)}</pre></section>}
  </main>;
}
