import { useEffect, useState } from "react";
import InvestigationReportPage from "./pages/InvestigationReportPage";

const analysisSteps = ["Parsing email", "Extracting indicators", "Checking authentication", "Analyzing infrastructure", "Checking reputation", "Correlating campaigns", "Computing risk"];
const Mark = () => <div className="brand-mark" aria-hidden="true">⌁</div>;

function Topbar({ theme, setTheme, onHome, view, setView }) {
  return <header className="topbar"><button className="brand" onClick={onHome}><Mark /><span className="brand-name">Mail<span>Sentinel</span></span></button><nav className="top-nav"><button className={view === "report" ? "active" : ""} onClick={() => setView("report")}>Investigations</button><button className={view === "history" ? "active" : ""} onClick={() => setView("history")}>History</button><button className={view === "settings" ? "active" : ""} onClick={() => setView("settings")}>Settings</button></nav><button className="theme-toggle" onClick={() => setTheme(theme === "dark" ? "light" : "dark")}><span>{theme === "dark" ? "☀" : "☾"}</span><span>{theme === "dark" ? "Light" : "Dark"}</span></button></header>;
}
const NetworkBackdrop = () => <div className="network-backdrop" aria-hidden="true"><i /><i /><i /><i /><b /><b /><b /><b /></div>;
function Landing({ onAnalyze }) {
  const [dragging, setDragging] = useState(false), [fileName, setFileName] = useState(""), [error, setError] = useState("");
  const choose = (file) => { if (!file) return; if (!file.name.toLowerCase().endsWith(".eml")) { setError("MailSentinel needs the original .eml message to retain forensic headers."); return; } setError(""); setFileName(file.name); };
  return <main className="landing"><NetworkBackdrop /><section className="upload-hero"><div className="eyebrow"><span /> EMAIL THREAT FORENSICS</div><h1>From inbox <em>→</em> infrastructure <em>→</em> campaign</h1><p>Turn a suspicious message into an explainable investigation—headers, infrastructure, authentication, and campaign intelligence in one defensible report.</p><label className={`drop-zone ${dragging ? "dragging" : ""}`} onDragOver={(e) => { e.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(e) => { e.preventDefault(); setDragging(false); choose(e.dataTransfer.files[0]); }}><input type="file" accept=".eml,message/rfc822" onChange={(e) => choose(e.target.files[0])} /><div className="upload-orb">↑</div><strong>{fileName || "Drop a .eml file here"}</strong><span>{fileName ? "Ready for investigation" : "or click to browse from your device"}</span>{error && <small className="upload-error">{error}</small>}<button type="button" className="analyze-button" onClick={(e) => { e.preventDefault(); onAnalyze(fileName || "suspicious-email.eml"); }}>Analyze email <b>→</b></button><button type="button" className="sample-button" onClick={(e) => { e.preventDefault(); onAnalyze("sample-phishing-email.eml"); }}>Try a sample investigation</button></label><div className="capabilities"><span>AI ANALYSIS</span><i /> <span>EMAIL FORENSICS</span><i /> <span>CAMPAIGN CORRELATION</span></div></section><section className="how-it-works"><div><small>01</small><h2>Bring the original</h2><p>Export the message as an <b>.eml</b> file to preserve headers and routing evidence.</p></div><div><small>02</small><h2>Follow the evidence</h2><p>See exactly which signals contribute to the risk score and where they originate.</p></div><div><small>03</small><h2>Connect the campaign</h2><p>Compare verified, corroborated, and AI-inferred infrastructure links.</p></div></section></main>;
}
function Analyzing({ fileName, onDone }) {
  const [step, setStep] = useState(0);
  useEffect(() => { const id = setInterval(() => setStep((value) => { if (value === analysisSteps.length - 1) { clearInterval(id); setTimeout(onDone, 500); return value; } return value + 1; }), 420); return () => clearInterval(id); }, [onDone]);
  return <main className="analysis-screen"><NetworkBackdrop /><div className="analysis-card"><div className="analysis-radar"><span /><span /><span /><b>⌁</b></div><div className="eyebrow"><span /> INVESTIGATION IN PROGRESS</div><h1>Reading the signals.</h1><p className="analysis-file">{fileName}</p><ol>{analysisSteps.map((item, index) => <li className={index < step ? "done" : index === step ? "current" : ""} key={item}><span>{index < step ? "✓" : index === step ? "◌" : "·"}</span>{item}<small>{index < step ? "complete" : index === step ? "running" : "queued"}</small></li>)}</ol></div></main>;
}
function History({ openReport, newInvestigation }) { const items = [["HIGH", "fake-bank.xyz", "87", "Today · 09:14"], ["MEDIUM", "parcel-delivery.support", "54", "Yesterday · 16:42"], ["SAFE", "accounts.google.com", "12", "Sep 10 · 11:08"]]; return <main className="workspace-page"><div className="workspace-heading"><div><div className="eyebrow"><span /> INVESTIGATION ARCHIVE</div><h1>Recent investigations</h1><p>Review historic email decisions and their connected infrastructure.</p></div><button className="analyze-button" onClick={newInvestigation}>+ New investigation</button></div><div className="archive-list">{items.map(([level, domain, score, time]) => <button className="archive-row" key={domain} onClick={openReport}><span className={`risk-pill ${level.toLowerCase()}`}>{level}</span><strong>{domain}</strong><span className="archive-time">{time}</span><span className="archive-score">{score}<small>/100</small></span><span>→</span></button>)}</div></main>; }
function Settings() { const [saved, setSaved] = useState(false); return <main className="workspace-page settings-page"><div className="workspace-heading"><div><div className="eyebrow"><span /> WORKSPACE</div><h1>Investigation settings</h1><p>Configure how MailSentinel presents and retains analysis results.</p></div></div><div className="settings-card"><div><h2>Analysis endpoint</h2><p>Connect this workspace to the MailSentinel backend when it is running.</p></div><label>Endpoint<input defaultValue="http://localhost:5001/analyze" /></label><label className="switch-row">Keep investigations in this browser <input type="checkbox" defaultChecked /></label><button className="analyze-button" onClick={() => setSaved(true)}>{saved ? "✓ Settings saved" : "Save settings"}</button></div></main>; }
export default function App() { const [theme, setTheme] = useState("dark"), [view, setView] = useState("landing"), [fileName, setFileName] = useState(""); useEffect(() => document.documentElement.setAttribute("data-theme", theme), [theme]); const home = () => setView("landing"); const start = (name) => { setFileName(name); setView("analyzing"); }; return <div className="app-shell"><Topbar theme={theme} setTheme={setTheme} onHome={home} view={view} setView={setView} />{view === "landing" && <Landing onAnalyze={start} />}{view === "analyzing" && <Analyzing fileName={fileName} onDone={() => setView("report")} />}{view === "report" && <InvestigationReportPage onNewInvestigation={home} />}{view === "history" && <History openReport={() => setView("report")} newInvestigation={home} />}{view === "settings" && <Settings />}</div>; }
